# Generated by Django 6.0.1 on 2026-01-23 10:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_productcolor_productimage_productvariant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Средний рейтинг'),
        ),
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во отзывов'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка (1-5)')),
                ('text', models.TextField(blank=True, verbose_name='Отзыв')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'is_published'], name='shop_produc_product_52737b_idx'), models.Index(fields=['product', 'created_at'], name='shop_produc_product_56c4ce_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('product', 'user'), name='uniq_review_per_user_product')],
            },
        ),
    ]
